version: 1
services:
  - type: web
    name: amazon-bot
    env: python
    plan: free
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
