version: 1
services:
  - type: web
    name: amazon-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bot.py"
    routes:
      - src: /
        dest: amazon-bot.wsgi:application
